In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn import tree
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine

In [3]:
df = pd.read_csv('groundwater_ml_dataset_cleaned.csv')
df

,state,district,annual_recharge,extractable_resource,annual_extraction,stage_of_development,category,extraction_ratio,utilization_rate,stress_level,risk_score,year
0,Himachal Pradesh,Himachal Pradesh,0.61,0.18,0.13,0.20,Safe,0.213115,0.722222,0.0020,0.374535,2024
1,Madhya Pradesh,Madhya Pradesh,27.00,1.68,0.17,7.04,Safe,0.006296,0.101190,0.0704,0.057075,2024
2,Andhra Pradesh,Alluri Sitharama Raju,43956.31,102516.48,2860.84,8890.60,Over Exploited,0.065084,0.027906,88.9060,17.818396,2024
3,Andhra Pradesh,Anakapalli,22443.69,38195.76,14423.44,6889.74,Over Exploited,0.642650,0.377619,68.8974,14.187588,2024
4,Andhra Pradesh,Ananthapuramu,40986.63,44150.14,1323.64,35512.65,Over Exploited,0.032294,0.029980,355.1265,71.050210,2024
...,...,...,...,...,...,...,...,...,...,...,...,...
753,Uttar Pradesh,Amethi,2329.92,2068.95,88.80,260.97,Over Exploited,0.038113,0.042920,2.6097,0.554353,2024
754,Uttar Pradesh,Bareilly,4120.00,3244.34,78.75,540.15,Over Exploited,0.019114,0.024273,5.4015,1.097655,2024
755,Uttar Pradesh,Jhansi,4619.37,2644.95,57.26,1974.42,Over Exploited,0.012396,0.021649,19.7442,3.962458,2024
756,Madhya Pradesh,Madhya Pradesh,317.00,1.00,2.00,314.00,Over Exploited,0.006309,2.000000,3.1400,1.430524,2024
757,Ladakh,Ladakh,18.00,5.00,0.00,13.00,Safe,0.000000,0.000000,0.1300,0.026000,2024

In [4]:
df.isnull().sum()

state                   0
district                0
annual_recharge         0
extractable_resource    0
annual_extraction       0
stage_of_development    0
category                0
extraction_ratio        0
utilization_rate        0
stress_level            0
risk_score              0
year                    0
dtype: int64

In [5]:
num_cols = df.select_dtypes('number').columns # Selecting numerical columns
print(num_cols.tolist())

['annual_recharge', 'extractable_resource', 'annual_extraction', 'stage_of_development', 'extraction_ratio', 'utilization_rate', 'stress_level', 'risk_score', 'year']

In [6]:
cat_cols = df.select_dtypes(exclude='number').columns # Exclude numerical columns to get categorical columns
print(cat_cols.tolist())

['state', 'district', 'category']

In [7]:
cat_enc = OneHotEncoder(drop='first') # Using OneHotEncoder to convert categorical variable '
cat_dummy = cat_enc.fit_transform(df[['category']]).toarray() # Convert to dummy variables
cat_dummy_df = pd.DataFrame(cat_dummy, columns=cat_enc.get_feature_names_out(['category'])) # Convert to DataFrame

In [8]:
cat_dummy_df

     category_Over Exploited  category_Safe  category_Semi Critical
0                        0.0            1.0                     0.0
1                        0.0            1.0                     0.0
2                        1.0            0.0                     0.0
3                        1.0            0.0                     0.0
4                        1.0            0.0                     0.0
..                       ...            ...                     ...
753                      1.0            0.0                     0.0
754                      1.0            0.0                     0.0
755                      1.0            0.0                     0.0
756                      1.0            0.0                     0.0
757                      0.0            1.0                     0.0

[758 rows x 3 columns]

In [9]:
cat_cols = ['state', 'district']
state_enc = OneHotEncoder(drop='first') # Using OneHotEncoder to convert categorical variables
dummy_cols = state_enc.fit_transform(df[cat_cols]).toarray() # Convert to dummy variables
dummy_df = pd.DataFrame(dummy_cols, columns=state_enc.get_feature_names_out(cat_cols)) # Convert to DataFrame

In [10]:
df['state'].value_counts()

state
Uttar Pradesh        123
Bihar                 99
Andhra Pradesh        82
Chhattisgarh          77
Gujarat               60
Assam                 54
Karnataka             43
Haryana               42
Jharkhand             41
Jammu And Kashmir     40
Kerala                38
Arunachal Pradesh     22
Odisha                 5
Madhya Pradesh         4
Tamil Nadu             4
Ladakh                 3
Lakshadweep            3
Meghalaya              2
Nagaland               2
Punjab                 2
Rajasthan              2
Telangana              2
Tripura                2
Uttarakhand            2
West Bengal            2
Himachal Pradesh       1
Manipur                1
Name: count, dtype: int64

In [11]:
df['state'].value_counts()

state
Uttar Pradesh        123
Bihar                 99
Andhra Pradesh        82
Chhattisgarh          77
Gujarat               60
Assam                 54
Karnataka             43
Haryana               42
Jharkhand             41
Jammu And Kashmir     40
Kerala                38
Arunachal Pradesh     22
Odisha                 5
Madhya Pradesh         4
Tamil Nadu             4
Ladakh                 3
Lakshadweep            3
Meghalaya              2
Nagaland               2
Punjab                 2
Rajasthan              2
Telangana              2
Tripura                2
Uttarakhand            2
West Bengal            2
Himachal Pradesh       1
Manipur                1
Name: count, dtype: int64

In [12]:
cat_dummy_df

     category_Over Exploited  category_Safe  category_Semi Critical
0                        0.0            1.0                     0.0
1                        0.0            1.0                     0.0
2                        1.0            0.0                     0.0
3                        1.0            0.0                     0.0
4                        1.0            0.0                     0.0
..                       ...            ...                     ...
753                      1.0            0.0                     0.0
754                      1.0            0.0                     0.0
755                      1.0            0.0                     0.0
756                      1.0            0.0                     0.0
757                      0.0            1.0                     0.0

[758 rows x 3 columns]

In [13]:
clean_df = pd.concat([df, dummy_df, cat_dummy_df], axis=1).drop(columns = cat_cols +['category']) # Dropping original categorical columns and concatenating dummy variables
clean_df

,annual_recharge,extractable_resource,annual_extraction,stage_of_development,extraction_ratio,utilization_rate,stress_level,risk_score,year,state_Arunachal Pradesh,...,district_Vizianagaram,district_WEST KAMENG,district_WEST SIANG,district_Wayanad,district_West Godavari,district_West Singhbhum,district_Y.S.R Kadapa,category_Over Exploited,category_Safe,category_Semi Critical
0,0.61,0.18,0.13,0.20,0.213115,0.722222,0.0020,0.374535,2024,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,27.00,1.68,0.17,7.04,0.006296,0.101190,0.0704,0.057075,2024,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,43956.31,102516.48,2860.84,8890.60,0.065084,0.027906,88.9060,17.818396,2024,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,22443.69,38195.76,14423.44,6889.74,0.642650,0.377619,68.8974,14.187588,2024,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,40986.63,44150.14,1323.64,35512.65,0.032294,0.029980,355.1265,71.050210,2024,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,2329.92,2068.95,88.80,260.97,0.038113,0.042920,2.6097,0.554353,2024,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
754,4120.00,3244.34,78.75,540.15,0.019114,0.024273,5.4015,1.097655,2024,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
755,4619.37,2644.95,57.26,1974.42,0.012396,0.021649,19.7442,3.962458,2024,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
756,317.00,1.00,2.00,314.00,0.006309,2.000000,3.1400,1.430524,2024,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
757,18.00,5.00,0.00,13.00,0.000000,0.000000,0.1300,0.026000,2024,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [14]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [15]:
X = clean_df.drop(['risk_score'], axis=1)
y = df['risk_score']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
X

,annual_recharge,extractable_resource,annual_extraction,stage_of_development,extraction_ratio,utilization_rate,stress_level,year,state_Arunachal Pradesh,state_Assam,...,district_Vizianagaram,district_WEST KAMENG,district_WEST SIANG,district_Wayanad,district_West Godavari,district_West Singhbhum,district_Y.S.R Kadapa,category_Over Exploited,category_Safe,category_Semi Critical
0,0.61,0.18,0.13,0.20,0.213115,0.722222,0.0020,2024,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,27.00,1.68,0.17,7.04,0.006296,0.101190,0.0704,2024,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,43956.31,102516.48,2860.84,8890.60,0.065084,0.027906,88.9060,2024,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,22443.69,38195.76,14423.44,6889.74,0.642650,0.377619,68.8974,2024,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,40986.63,44150.14,1323.64,35512.65,0.032294,0.029980,355.1265,2024,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,2329.92,2068.95,88.80,260.97,0.038113,0.042920,2.6097,2024,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
754,4120.00,3244.34,78.75,540.15,0.019114,0.024273,5.4015,2024,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
755,4619.37,2644.95,57.26,1974.42,0.012396,0.021649,19.7442,2024,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
756,317.00,1.00,2.00,314.00,0.006309,2.000000,3.1400,2024,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
757,18.00,5.00,0.00,13.00,0.000000,0.000000,0.1300,2024,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [18]:
y

0       0.374535
1       0.057075
2      17.818396
3      14.187588
4      71.050210
         ...
753     0.554353
754     1.097655
755     3.962458
756     1.430524
757     0.026000
Name: risk_score, Length: 758, dtype: float64

In [19]:
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [20]:
import joblib

# Save the trained model
joblib.dump(rf, 'random_forest_model.pkl')
print("Model saved as 'random_forest_model.pkl'")

Model saved as 'random_forest_model.pkl'

In [21]:
y_pred = rf.predict(X_test)

In [22]:
print("accuracy_score: ", rf.score(X_test, y_test))

accuracy_score:  0.9970148602589755